/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HumanlockRouteImport } from './routes/humanlock'
import { Route as AgentpassRouteImport } from './routes/agentpass'
import { Route as IndexRouteImport } from './routes/index'

const HumanlockRoute = HumanlockRouteImport.update({
  id: '/humanlock',
  path: '/humanlock',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentpassRoute = AgentpassRouteImport.update({
  id: '/agentpass',
  path: '/agentpass',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agentpass': typeof AgentpassRoute
  '/humanlock': typeof HumanlockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agentpass': typeof AgentpassRoute
  '/humanlock': typeof HumanlockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agentpass': typeof AgentpassRoute
  '/humanlock': typeof HumanlockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agentpass' | '/humanlock'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agentpass' | '/humanlock'
  id: '__root__' | '/' | '/agentpass' | '/humanlock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentpassRoute: typeof AgentpassRoute
  HumanlockRoute: typeof HumanlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/humanlock': {
      id: '/humanlock'
      path: '/humanlock'
      fullPath: '/humanlock'
      preLoaderRoute: typeof HumanlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentpass': {
      id: '/agentpass'
      path: '/agentpass'
      fullPath: '/agentpass'
      preLoaderRoute: typeof AgentpassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentpassRoute: AgentpassRoute,
  HumanlockRoute: HumanlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
